EPMDJ-5963 and EPMDJ-6065 Fix start session for offline agent and fix multinstances agent is busy when one of nodes is up
Drill4J/admin pull request #153
Opened 2021-02-12 17:28 UTC by Mazel-Tovr

2021-02-12 18:27 UTC, Mazel-Tovr commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +        info.persistToDatabase()
i should persist after copy

2021-04-05 09:30 UTC, ViktoriiaLebedeva requested changes

2021-04-05 09:30 UTC, ViktoriiaLebedeva commented on tests/src/test/kotlin/e2e/AgentSingleInstanceTest.kt
> +                agent.`get-load-classes-datas`()
Why did you do this only in this test?

2021-05-12 14:05 UTC, Mazel-Tovr commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +        }
add logging

2021-05-12 14:11 UTC, Mazel-Tovr commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +data class InstanceInfo(
InstanceState

2021-05-12 14:15 UTC, Mazel-Tovr commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +    fun getActualAgentStatus(agentId: String): AgentStatus = instanceIds(agentId).let { instances ->
AgentStatus

2021-05-12 14:21 UTC, Mazel-Tovr commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +    ) {
reduce amount of param

2021-05-18 07:29 UTC, LikhanovMaxim approved these changes

2021-05-18 07:29 UTC, LikhanovMaxim commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +                if (instance?.all { it.value.status != AgentStatus.BUSY } == true) {
smth strange condition

2021-05-18 09:26 UTC, ViktoriiaLebedeva requested changes

2021-05-18 09:26 UTC, ViktoriiaLebedeva commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +    fun getStatus(agentId: String): AgentStatus = instanceIds(agentId).let { instances ->
Can you check this variant of these function 
`fun getStatus(agentId: String): AgentStatus = instanceIds(agentId).takeIf { it.isNotEmpty() }?.let { instances ->
        entryOrNull(agentId)?.agent?.takeIf { it.isRegistered }?.let {
            val statuses = instances.map { it.value.status }.distinct()
            AgentStatus.ONLINE.takeIf { AgentStatus.ONLINE in statuses } ?: AgentStatus.BUSY
        } ?: AgentStatus.NOT_REGISTERED
    } ?: AgentStatus.OFFLINE`
Offline status can be only if agent doesn't have instances.

2021-05-18 09:26 UTC, ViktoriiaLebedeva commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +            if (instance?.all { it.value.status == AgentStatus.BUSY } == true) {
simplify boolean expression to if(instance.all { it.value.status == AgentStatus.BUSY })

2021-05-18 09:26 UTC, ViktoriiaLebedeva commented on core/src/main/kotlin/endpoints/AgentManager.kt
> +        updateInstanceStatus(instanceKey, AgentStatus.BUSY).also { instance ->
Move the null check here, before also.

2021-05-19 15:21 UTC, merged