EPMDJ-1402. Solved the problem with run admin server on Java>=9.
Drill4J/admin pull request #21
Opened 2020-01-13 10:24 UTC by ViktoriiaLebedeva

2020-01-13 11:09 UTC, IgorKey commented on core/src/main/kotlin/com/epam/drill/PluginClassLoader.kt
> +class PluginClassLoader(url:URL) : URLClassLoader(arrayOf(url)) {
FORMATTING.

2020-01-13 11:12 UTC, IgorKey commented on core/src/main/kotlin/com/epam/drill/PluginClassLoader.kt
> +        logger.debug {"Loading class with name $name"}
so weird. Method 'findClass' but log like loading... why?

2020-01-13 13:07 UTC, viktorbll commented on core/src/main/kotlin/com/epam/drill/PluginClassLoader.kt
> +package com.epam.drill
The code must reside under the "com.epam.drill.admin" package

2020-01-14 10:06 UTC, viktorbll requested changes

2020-01-14 10:06 UTC, viktorbll commented on core/src/main/kotlin/com/epam/drill/admin/PluginClassLoader.kt
> +package com.epam.drill.admin
com.epam.drill.admin.plugin

2020-01-14 16:57 UTC, viktorbll commented on core/src/main/kotlin/com/epam/drill/plugins/PluginLoaderService.kt
>          return pluginApiClass as Class<AdminPluginPart<*>>?
`pluginApiClass as? Class<AdminPluginPart<*>>`

2020-01-14 16:58 UTC, viktorbll commented on core/src/main/kotlin/com/epam/drill/plugins/PluginLoaderService.kt
> +        val pluginClassLoader =
this newline is unnecessary

2020-01-15 07:55 UTC, viktorbll approved these changes

2020-01-15 07:56 UTC, merged