Feature/authorization and authentication epmdj 10645
Drill4J/admin pull request #318
Opened 2023-10-02 12:46 UTC by iryabov

2023-10-02 12:50 UTC, iryabov commented on gradle.properties
> +ktorVersion = 1.6.8
I tried to fix the [issue ](https://youtrack.jetbrains.com/issue/KTOR-2794) with supporting application.conf in tests. But it did not help.

2023-10-03 10:03 UTC, RomanDavlyatshin requested changes

2023-10-03 10:03 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/jwt/config/JwtConfig.kt
> +    get() = jwtProperties.propertyOrNull("issuer")?.getString() ?: "Drill4j App"
"Drill4j App" -> "Drill4J App"

2023-10-03 10:03 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/core/WsExtension.kt
> +    jwtConfig: JwtConfig,
Use static import instead of parameter.
We import it statically everywhere anyway, why use the parameter here. Since it not configurable we can treat it as an implementation detail

2023-10-03 10:03 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/jwt/config/JwtConfig.kt
> +class JwtConfig(
Reason for swapping `object` with `class` - I think `JwtConfig` could be singleton

2023-10-03 10:03 UTC, RomanDavlyatshin commented on tests/src/test/kotlin/com/epam/drill/admin/e2e/AgentRegistrationTest.kt
> +        createSimpleAppWithUIConnection(uiStreamDebug = true, agentStreamDebug = true) {
reason for removing timeout

2023-10-03 10:03 UTC, RomanDavlyatshin commented on admin-core/src/main/resources/application.conf
> +        realm = "Drill4j App"
"Drill4j App" -> "Drill4J App"

2023-10-03 10:03 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/jwt/config/JwtConfig.kt
> +val Application.jwtSecret: String
Won't it be better to extend `JwtConfig` with those methods and not `Application`?

2023-10-03 10:09 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/jwt/config/JwtConfig.kt
> +class JwtConfig(
Cannot set properties of object after object creation

2023-10-03 10:13 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/jwt/config/JwtConfig.kt
> +val Application.jwtSecret: String
`val Application.jwtProperties: ApplicationConfig get() = drillConfig.config("jwt")` dependes on Application instance - it'll be hard to change that

2023-10-03 10:16 UTC, RomanDavlyatshin commented on admin-core/src/main/kotlin/com/epam/drill/admin/core/WsExtension.kt
> +    jwtConfig: JwtConfig,
`jwtConfig` is obtained via Application extension, hence no static import

2023-10-04 07:32 UTC, iryabov commented on admin-core/src/main/resources/application.conf
> +        realm = "Drill4j App"
It will be removed after merge #319

2023-10-04 10:09 UTC, merged