EPMDJ-2344.Fixed incorrect content-type and examples of responses.
Drill4J/admin pull request #32
Opened 2020-02-06 14:23 UTC by ViktoriiaLebedeva

2020-02-10 07:57 UTC, viktorbll requested changes
Too much refactoring for such simple change.
The task is not about refactoring.
Change to empty content leads to information loss in some cases.

2020-02-10 07:58 UTC, viktorbll commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
> +                            HttpStatusCode.OK to EmptyContent
information is lost in this case

2020-02-10 08:46 UTC, LikhanovMaxim commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
>                      logger.info { "Read notification" }
This is not enough informative log, we should add 'notificationId'

2020-02-11 10:56 UTC, LikhanovMaxim approved these changes
Approved in case that we have created a task with redesign endpoints: notifications/read & notifications/delete

2020-02-11 13:29 UTC, viktorbll commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
> +                post<Routes.Api.ReadNotification, NotificationId>(notificationResponds) { _, (notificationId) ->
revert this

2020-02-11 13:30 UTC, viktorbll commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
> +                post<Routes.Api.DeleteNotification, NotificationId>(notificationResponds) { _, (notificationId) ->
revert this

2020-02-13 10:35 UTC, merged