Feature/oauth2 user mapping epmdj 10714
Drill4J/admin pull request #348
Opened 2023-11-23 10:04 UTC by iryabov

Features:
- Configurable mapping between oauth2 access token claims and user attributes (username, roles etc.)
- Configurable mapping between user info response and user attributes
- Configurable mapping between OAuth2 roles and Drill4J roles
- Calling OAuth2 user-info service is optional
- OAuth2 roles mapping is optional

For discussion:
- I believe that in OAuth2 providers there is more often a list of roles than one role, so in the mapping there are only "roles" mapping and no "role" mapping.
- If userInfoUrl is not specified, the access token is mapped, and vice versa, if userInfoUrl is present, only the user-info response is mapped. Should combine mapping of both?

2023-11-28 13:47 UTC, RomanDavlyatshin requested changes

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +    fun `given token mapping config, mapAccessTokenToUserEntity must map access token data to user entity`() {
`mapAccessTokenToUserEntity` -> `mapAccessTokenContentToUserEntity`? _tbd_

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +        val oauthConfig = OAuthConfig(MapApplicationConfig().apply {
Might as well skip creating `oauthConfig` val
```
val oauthMapper = OAuthMapperImpl(OAuthConfig(MapApplicationConfig().apply {
 /*...*/
}))
```

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +            JWT.create()
I suggest assigning `JWT.create()` call to `val` above - just for clarity and distinct "arrange/act/assert" test structure
```
val ouathMapper = /*...*/
val externalJwt = /*...*/

val userEntity = ouathMapper.mapAccessTokenToUserEntity(externalJwt)

assertEquals("some-username", userEntity.username)
assertEquals(Role.USER.name, userEntity.role)
```

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +            """
move user info definition to `val userInfo`  above

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
> +    ): String = runCatching {
Returning `String` here seems odd:
- I don't get the reasoning behind it
- can't httpClient do the mapping to JSON for us, using `content-type:application/json` as a hint? 😮

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +            JWT.create()
move to the `val` above

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +            // no username mapping, default value is "sub"
_tbd_ I don't understand the reasoning for using `"sub"`

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +                .withSubject("some-username")  //this is claim "sub"
_tbd_

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +    fun `given not matchable username token mapping config, mapAccessTokenToUserEntity must fail`() {
"not matchable" is definition is unclear to me (I don't understand the case)

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthServiceTest.kt
> +            whenever(oauthMapper.mapUserInfoToUserEntity(testUserInfoResponse)).thenReturn(
what is the point in mocking httpCall to `"/userInfoUrl"` and passing `testUserInfoResponse` manually at the same time?

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthServiceTest.kt
> +        override fun answer(invocation: InvocationOnMock?) = invocation?.getArgument<UserEntity>(0)?.copy(id = 123)
_tbd_ how exactly does it work?

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
> +        ?.let { oauthMapper.mergeUserEntities(dbUser, oauthUser) }
having `dbUser` and `oauthUser` parameters swap places for no reason is confusing - keep order of params

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
>          val dbUser = userRepository.findByUsername(oauthUser.username)
this operation might as well be moved to `createOrUpdate` user function - in that case it'll accept a single param, which will be more straightforward

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +    override fun mergeUserEntities(userFromDatabase: UserEntity, userFromOAuth: UserEntity): UserEntity {
more like `fun updateDbUserEntity(dbUser: UserEntity, userFromOAuth: UserEntity)`?

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +        return JWT.decode(accessToken).toUserEntity(tokenMapping)
handle malformed data error

2023-11-28 13:47 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +        return Json.parseToJsonElement(userInfoResponse).toUserEntity(userInfoMapping)
handle malformed json error

2023-11-28 13:51 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
> +    ): String = runCatching {
`/user-info` can return anything (plaintext, xml), not just json

2023-11-28 13:53 UTC, RomanDavlyatshin requested changes

2023-11-28 13:53 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/config/OAuthConfig.kt
> +                username = propertyOrNull("username")?.getString() ?: "sub",
add comment with a link to access token standard

2023-11-28 13:53 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +            // no username mapping, default value is "sub"
this is a part of "access token" standard. TODO - add link

2023-11-28 13:53 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +                .withSubject("some-username")  //this is claim "sub"
see prev comment

2023-11-28 13:56 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +    fun `given not matchable username token mapping config, mapAccessTokenToUserEntity must fail`() {
`if drill.auth.oauth2.tokenMapping.username value is not present in token content, mapAccessTokenToUserEntity must fail`

2023-11-28 13:56 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthMapperTest.kt
> +    fun `given not matchable username token mapping config, mapAccessTokenToUserEntity must fail`() {
not matchable -> key we have specified in mapping cannot be found in token content

2023-11-28 14:00 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthServiceTest.kt
> +            whenever(oauthMapper.mapUserInfoToUserEntity(testUserInfoResponse)).thenReturn(
it is used later to verify it was passed and handled correctly between services

2023-11-28 14:32 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/OAuthServiceTest.kt
> +        override fun answer(invocation: InvocationOnMock?) = invocation?.getArgument<UserEntity>(0)?.copy(id = 123)
`.thenAnswer` is a part of mocking process -> since userRepository is mocked we need to assign id to the returned user

2023-11-28 14:37 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
>          val dbUser = userRepository.findByUsername(oauthUser.username)
having "blocked" check in createOrUpdate would be odd

2023-11-28 14:40 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +        return JWT.decode(accessToken).toUserEntity(tokenMapping)
TODO - check that it throws internal server error

2023-11-28 14:41 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +        return Json.parseToJsonElement(userInfoResponse).toUserEntity(userInfoMapping)
see prev comment

2023-11-29 11:41 UTC, iryabov commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthMapperImpl.kt
> +        return JWT.decode(accessToken).toUserEntity(tokenMapping)
Yes, if OAuthMapperImpl throws JWTDecodeException or SerializationException then Ktor will catch them and handle by default status page handler, as a result will return 500 status page and will log a message.

2023-11-29 12:16 UTC, merged