Feature/prevent self destructing epmdj 10711
Drill4J/admin pull request #349
Opened 2023-11-23 14:23 UTC by iryabov

2023-11-28 14:53 UTC, RomanDavlyatshin requested changes

2023-11-28 14:53 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/UserAuthenticationServiceImpl.kt
> +        id = this.id!!, //the user entity must be inserted and have id
Avoid using null-check op since it throws bare NPE without any context
I suggest to either handle it, or better yet add check before constructing `UserInfoView()` to explicitly state that `this.id` must not be null

2023-11-28 14:53 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
>  private fun UserEntity.toView() = UserInfoView(
we do have almost the same function at `UserAuthenticationServiceImpl.kt`

2023-11-28 14:53 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/route/UserAuthenticationRoutes.kt
> +    exception<SelfDestructException> { cause ->
1. I would rather call it something less extreme 😄 
e.g. `ForbiddenOperation` with error `"Cannot modify own profile"`
2. we intend to show this error on UI, so that must have a clear message - no need to include HTTP status code in the message itself

2023-11-28 14:53 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/UserAuthenticationServiceImpl.kt
> +        id = this.id!!, //the user entity must be inserted and have id
already address in the next pr

2023-11-28 14:55 UTC, RomanDavlyatshin requested changes

2023-11-28 14:55 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
>  private fun UserEntity.toView() = UserInfoView(
move extension function to `UserInfoView`

2023-11-29 12:02 UTC, iryabov commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/OAuthServiceImpl.kt
>  private fun UserEntity.toView() = UserInfoView(
Will be done in the PR #351

2023-11-29 12:13 UTC, iryabov commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/route/UserAuthenticationRoutes.kt
> +    exception<SelfDestructException> { cause ->
1, Change to ForbiddenOperationException
2. This is just a log entry and is not shown to users.

2023-11-29 12:41 UTC, merged