Feature/user registration date epmdj 10712
Drill4J/admin pull request #351
Opened 2023-11-24 10:26 UTC by iryabov

For discussion:
- I decided to make the registration date as a nullable field because I don't like default value as "0" for dates and not only that
- I decided to set the registration date to current date inside the UserRepositoryImpl otherwise it would not be possible to test with the mocked UserRepository.

2023-11-28 15:02 UTC, RomanDavlyatshin requested changes

2023-11-28 15:02 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/UserRepositoryImplTest.kt
> +    fun `given not specified registration date, create must insert user and return registration date equal to current time`() =
I don't really like the approach since it introduces indeterminism
Time functions are commonly abstracted (with either DI framework or just a parameter of function/class field) - it makes it easy to mock them and make tests repeatable
_tbd_

2023-11-28 15:02 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/UserManagementTests.kt
> +                assertEquals(testRegistrationDate.toKotlinLocalDateTime(), response.registrationDate)
is asserting time really necessary in _this_ test case?

2023-11-28 15:02 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/UserRepositoryImplTest.kt
> +    fun `given not specified registration date, create must insert user and return registration date equal to current time`() =
`DatabaseUserRepository(dateNowProvider = {LocalDate.date.now()})`

2023-11-29 12:03 UTC, iryabov commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/service/impl/UserAuthenticationServiceImpl.kt
>  private fun UserEntity.toView(): UserInfoView {
move extension function to UserInfoView

2023-11-29 13:07 UTC, merged