Feature/create api for api keys epmdj 10730
Drill4J/admin pull request #356
Opened 2023-12-05 14:39 UTC by iryabov

2023-12-11 13:32 UTC, RomanDavlyatshin requested changes

2023-12-11 13:32 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/entity/ApiKeyEntity.kt
> +    val user: UserEntity,
motivation for keeping the whole entity, rather than the user id

2023-12-11 13:32 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/entity/ApiKeyEntity.kt
> +    val expired: LocalDateTime,
`expired` -> `expiresAt`

2023-12-11 13:32 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/model/ApiKeyModels.kt
> +    val username: String,
R we sure about having both `userId` and `username`?

2023-12-11 13:32 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/UserApiKeyTests.kt
> +                assertEquals(2, response.size)
I don't see the part where we populate repository width data or mock it. Am I missing something?

2023-12-11 13:35 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/entity/ApiKeyEntity.kt
> +    val user: UserEntity,
resolution: we won't store the whole entity, but rather the specific fields

2023-12-11 13:35 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/entity/ApiKeyEntity.kt
> +    val expired: LocalDateTime,
`created` -> `createdAt`

2023-12-11 13:37 UTC, RomanDavlyatshin commented on admin-auth/src/main/kotlin/com/epam/drill/admin/auth/model/ApiKeyModels.kt
> +    val username: String,
we need userId to allow navigating/performing user-related operations

2023-12-11 13:37 UTC, RomanDavlyatshin commented on admin-auth/src/test/kotlin/com/epam/drill/admin/auth/UserApiKeyTests.kt
> +                assertEquals(2, response.size)
not implemented yet

2023-12-12 10:38 UTC, merged

2023-12-12 10:50 UTC, iryabov commented
Should be discussed:
I decided that the `ApiKeyView` for management purposes should contain information about the username, user role, etc., but the `UserApiKeyView` should not because they are already in the context of the current user.
So I added a nullable user field to the ApiKeyEntity. For management purposes, `api_key` table will be joined with the `user` table in the database, but in case of user purposes it will not be. This is for SQL optimization.