feat: add /tests-to-skip route and a stub implementation
Drill4J/admin pull request #402
Opened 2024-11-25 11:00 UTC by iryabov

EPMDJ-10877

2024-11-25 15:28 UTC, RomanDavlyatshin requested changes

2024-11-25 15:28 UTC, RomanDavlyatshin commented on admin-metrics/src/main/kotlin/com/epam/drill/admin/metrics/route/response/TestResponse.kt
I suggest we keep it similar to `admin-writer` implementation  - we can use entity from `admin-writer/src/main/kotlin/com/epam/drill/admin/writer/rawdata/entity/TestMetadata.kt` and introduce `/view/TestToSkipView`

2024-12-12 11:49 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +			risks.__signature AS signature,
formatting is off

2024-12-12 11:49 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +    TargetMethods AS (
Can we use `raw_data.get_methods` fn here?

2024-12-12 11:49 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +            methods.signature as signature,
no need to explicitly add `as` for each column if name is not changed

2024-12-12 11:49 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +			(target.body_checksum != coverage.body_checksum) AS has_risk
aliases made this condition very confusing

2024-12-12 11:49 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +			(target.body_checksum != coverage.body_checksum) AS has_risk
`has_risk` is never checked to be "false" -> all the records containing "false" values are never used -> can't we just filter them right away with JOIN condition?

2024-12-12 13:08 UTC, iryabov commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +			(target.body_checksum != coverage.body_checksum) AS has_risk
The column `hasRisk` uses in `TestsByRisks` CTE

2025-01-07 09:21 UTC, iryabov commented on admin-metrics/src/main/kotlin/com/epam/drill/admin/metrics/route/response/TestResponse.kt
How about to transfer common models as `TestMetadata` to the new `admin-common` module?

2025-01-08 10:21 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
> +			(target.body_checksum != coverage.body_checksum) AS has_risk
`has_risk` -> `is_modified`

2025-01-08 10:27 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/V6__Methods_Coverage_Mat_View.sql
Change V6__ to R__Mat_Views to avoid spamming V__ migrations for mat view changes AND keep mat views separated to avoid unnecessary updates to matviews when only metrics functions change

2025-01-08 10:34 UTC, RomanDavlyatshin commented on admin-writer/src/main/resources/raw_data/db/migration/R__Metrics_Functions.sql
R__Metric_Functions
R__Views
R__Matviews

2025-01-10 12:16 UTC, merged