EPMDJ-2360 Redesign notifications endpoints
Drill4J/admin pull request #52
Opened 2020-03-12 08:22 UTC by ViktoriiaLebedeva

2020-03-12 12:01 UTC, LikhanovMaxim requested changes
few comments

2020-03-12 12:01 UTC, LikhanovMaxim commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
>                      logger.info { "Notification was reed with result: $response" }
reed is a wrong word here)

2020-03-12 12:01 UTC, LikhanovMaxim commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
> +                        ok<Unit>(), notFound(), badRequest()
notFound(), badRequest()
is it necessary?

2020-03-12 12:01 UTC, LikhanovMaxim commented on core/src/main/kotlin/endpoints/openapi/DrillAdminEndpoints.kt
> +                        ok<Unit>(), notFound()
notFound()
is it necessary?

2020-03-12 12:01 UTC, LikhanovMaxim commented on core/src/main/kotlin/router/Routers.kt
> +        class Notifications
Why did you change 'notification**S**' to 'notification'?

2020-03-12 12:01 UTC, LikhanovMaxim commented on tests/src/test/kotlin/endpoints/DrillServerWsTest.kt
>                  getCurrentNotifications(incoming, outgoing)
Why do we invoke this method?

2020-03-12 12:01 UTC, LikhanovMaxim commented on tests/src/test/kotlin/endpoints/DrillServerWsTest.kt
>                  assertNotificationsCounters(currentNotifications, 3, 2)
Can we extract this type of block into methods?

2020-03-19 09:32 UTC, viktorbll commented on core/src/main/kotlin/notification/Manager.kt
> +        _notifications.update { it.minus(notifications.keys) }
minuы???

2020-03-19 09:35 UTC, viktorbll commented on core/src/main/kotlin/endpoints/ServerWsTopics.kt
> +                    notificationManager.notifications.values.reversed()
???

2020-03-20 11:09 UTC, viktorbll commented on core/src/main/kotlin/notification/Manager.kt
> +    private val _notifications = atomic(mapOf<String, Notification>().toPersistentMap())
persistentMapOf

2020-03-25 08:53 UTC, merged