EPMDJ-2416. Implemented agent logging config saving on admin side
Drill4J/admin pull request #74
Opened 2020-06-04 13:57 UTC by ViktoriiaLebedeva

2020-06-04 18:02 UTC, IgorKey commented on core/src/main/kotlin/agent/Model.kt
> +    var config: LoggingConfig = defaultLoggingConfig
u should try to avoid var modifier.

2020-06-10 14:30 UTC, viktorbll requested changes

2020-06-10 14:30 UTC, viktorbll commented on core/src/main/kotlin/agent/logging/Model.kt
> +fun LoggingConfig.withAgent(agentId: String) = AgentLoggingConfig(
this method is usless

2020-06-10 14:30 UTC, viktorbll commented on core/src/main/kotlin/agent/logging/Handler.kt
> +        sendToTopic<Communication.Agent.UpdateLoggingConfigEvent>(loggingConfig)
code style
```suggestion
    private suspend fun AgentWsSession.sendConfig(loggingConfig: LoggingConfig) { 
        sendToTopic<Communication.Agent.UpdateLoggingConfigEvent>(loggingConfig)
    }
```
this method is not part of the LoggingHandler

2020-06-10 16:24 UTC, viktorbll approved these changes

2020-06-10 16:25 UTC, merged